--select count (*) from customers;
--select * from customers;
--select Name as 'Customer', City from Customers;
--select * from Customers where city = 'cleveland'
--select * from Customers where city = 'Cleveland' or city ='Columbus'
--select * from customers where city in ('cleveland', 'colubus')
--select * from Customers order by sales desc
